version: '3'

services:
  db:
    image: mariadb
    container_name: mariadb
    env_file: ./.env
    volumes:
      - ~/docker/mariadb/etc/mysql/conf.d:/etc/mysql/conf.d:ro
      - ~/docker/mariadb/var/lib/mysql:/var/lib/mysql
      - ~/docker/mariadb/var/log/maria:/var/log/maria
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_DATABASE
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    networks:
      - backend
    platform: linux/x86_64

  web:
    image: 075584359222.dkr.ecr.ap-northeast-2.amazonaws.com/wemeet-dev-ecr
    container_name: web
    env_file: ./.env
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
      - redis
    networks:
      - backend

  redis:
    image: redis:7.0
    container_name: redis
    env_file: ./.env
    restart: always
    ports:
      - 6379:6379
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - backend

networks:
  backend: