spring:
  datasource:
    url: jdbc:h2:mem:testdb;Mode=MySQL
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  h2:
    console:
      enabled: true