spring:
  datasource:
    url: jdbc:h2:mem:testdb;Mode=MySQL
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  h2:
    console:
      enabled: true
  flyway:
    enabled: true
    locations: classpath:/db/migration
    baseline-on-migrate: true
  config:
    import: sub/application-jwt.yml, sub/application-aws.yml
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
    import: sub/dev/application-db.yml
---
spring:
  config:
    activate:
      on-profile: prod
