spring:
  datasource:
    url: jdbc:h2:mem:testdb;Mode=MySQL
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
  h2:
    console:
      enabled: true
  flyway:
    enabled: true
    locations: classpath:/db/migration
    baseline-on-migrate: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  config:
    import: sub/application-jwt.yml, sub/application-aws.yml, sub/application-enc.yml
  profiles:
    active: local

  mvc:
    static-path-pattern: /static/**

logging:
  file:
    path: ./logback-spring.xml

---
spring:
  config:
    activate:
      on-profile: local
    import: sub/local/application-db.yml
  sql:
    init:
      mode: always
      data-locations: classpath:sub/local/data.sql
---
spring:
  config:
    activate:
      on-profile: dev
    import: sub/dev/application-db.yml
  sql:
    init:
      mode: never
---
spring:
  config:
    activate:
      on-profile: prod
  sql:
    init:
      mode: never
