name: DEV-CD
on:
  push:
    branches:
      - develop
  pull_request:
jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: true
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'
      - name: Change Gradle version
        run: ./gradlew incrementVersion --versionIncrementType=PATCH
      - name: Build and push image to Amazon ECR
        run: ./gradlew clean jib -x test
      - name: Push Github
        run: |
          git config --global user.email "qkrdbsk28@naver.com"
          git config --global user.name "Chaerim1001"
          git add .
          git commit -m "deploy: push container image to ecr"
          git push origin HEAD:E2I-44-rim/build-cd-pipeline
