name: DEV-CD
on:
  push:
    branches:
      - develop
jobs:
  check-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check for Changes
        id: git-diff
        run: |
          changed_files=$(git diff --name-only)
          if [ -n "$changed_files" ]; then
            echo "::set-output name=changes::true"
          else
            echo "::set-output name=changes::false"
          fi

  deploy:
    needs: check-changes
    runs-on: ubuntu-latest
    if: needs.check-changes.outputs.changes == 'true'
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: true
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'
      - name: Change Gradle version
        run: ./gradlew incrementVersion --versionIncrementType=PATCH
      - name: Build and push image to Amazon ECR
        run: ./gradlew clean jib -x test
      - name: Push Github
        run: |
          git config --global user.email "qkrdbsk28@naver.com"
          git config --global user.name "Chaerim1001"
          git add .
          git commit -m "deploy: push container image to ecr"
          git push origin develop
